### ISSUE TITLE
Latest throws error

### ISSUE THREAD

**Issue by gurpal2000** [scolytus/gollum-docker#1]
Using the example command: 

`docker run -v $(pwd)/wiki:/wiki -p 127.0.0.1:3080:8080 scolytus/gollum:latest --port 8080 --emoji`

i see this error 

```
"Rugged::RepositoryError at /
could not find repository from '/wiki'"
```

docker log:

```
2020-05-17 00:33:27 - Rugged::RepositoryError - could not find repository from '/wiki':
        /usr/local/bundle/gems/gollum-rugged_adapter-1.0/lib/rugged_adapter/git_layer_rugged.rb:567:in `new'
        /usr/local/bundle/gems/gollum-rugged_adapter-1.0/lib/rugged_adapter/git_layer_rugged.rb:567:in `initialize'
        /usr/local/bundle/gems/gollum-lib-5.0.4/lib/gollum-lib/git_access.rb:16:in `new'
        /usr/local/bundle/gems/gollum-lib-5.0.4/lib/gollum-lib/git_access.rb:16:in `initialize'
etc
```

**Comment by scolytus** [comment]
@gurpal2000 Thanks for reporting.

This happens when the wiki directory is not an initialized git repository.

As a quick fix, on your host system, go to the wiki directory and initialize a git repository there:

```
$ cd wiki/
wiki$ git init .
```

I will check if this is a problem specific to the docker image or if this is also present in the installed version of gollum.

**Comment by scolytus** [comment]
Gollum requires an initialized git repository, this is not an issue specific to the container image.

I have updated the description on dockerhub.
